mysql:
  host: "localhost"
  port: 3306
  database: "yourdatabasename"
  username: "yourusername"
  password: "yourpassword"
  useSSL: false

debug-messages: false
join-command: true

lobby-location:
  world:
  x:
  y:
  z:
  yaw:
  pitch: