name: LuckyWars
version: 1.0.0
main: com.luckywars.game.LuckyWars
depend:
  - SlimeWorldManager
commands:
  luckywars:
    description: the main command of the command manager
    aliases:
      - lw
permissions:
  luckywars.command.member:
    description: Perm for command manager member version
    default: op
  luckywars.command.admin:
    description: Perm for the command manager
    default: op
  luckywars.command.party:
    description: Perm for party command
    default: op
  luckywars.command.setup:
    description: Perm for setup command
    default: op
  luckywars.command.test:
    description: Perm for test command
    default: op
  luckywars.command.gamelist:
    description: Perm for game list command
    default: op
  luckywars.command.reload:
    description: Perm for reload command
    default: op
  luckywars.command.setlobby:
    description: Perm for set lobby command
    default: op
  luckywars.command.build:
    description: Perm for build command
    default: op
  luckwars.command.delete:
    description: Perm for delete command
    default: op
  luckywars.command.join:
    description: Perm for join command
    default: op
  luckywars.command.locwand:
    description: Perm for loc wand command
    default: op